<?php
/*
FUNKCE
*/
include '../../fce.php';


$text = lang('
<h1>KURÁTOR 01: PŘEŽIJÍ JEN UMĚLCI</h1>
<p>Organizačním principem je v tomto případě autorský subjekt kurátorek. Jedná se o výraz solidarity představitelek výstavní instituce s dalšími aktéry současného umění v době krize; výraz osvobození se od omezení spojených s restriktivními preventivními opatřeními v době karantény a současně o gesto revolty vůči všeobecné kolektivní úzkosti a sentimentu skrze umělecký výzkum.</p>
<p>Kurátorský projekt Černá skříňka vznikl v době, kdy jsme prožívali nástup pandemie nového koronaviru způsobujícího onemocnění covid-19. Kurátorky Galerie TIC a členky kurátorské platformy Café Utopia Katarína Hládeková, Zuzana Janečková a Marika Kupková již 27. března 2020 vyzvaly ke spolupráci umělkyně a umělce, kteří ve své tvorbě reagují na koronavirovou krizi, a vytváří tak jedinečný záznam katastrofy, čímž nabízejí pozoruhodné indicie k pochopení dění uvnitř pomyslné černé skříňky.</p>
<p>Galerie a muzea byly v období koronavirové karantény uzavřeny. Ze dne na den. Nečekaně.Instituce na tuto situaci reagovaly tvorbou online programu: vysílané přednášky, komentované prohlídky, workshopy, to vše mělo nahrazovat standardní programovou nabídku. Tyto nepřesvědčivé pokusy o galerijní entertainment však standardní program nahradit nedokázaly. Chyběly smysluplné nápady, technické vybavení a osobní zkušenosti. Všemu navíc ještě vládla nadprodukce těchto aktivit, která v důsledku měla efekt zcela opačný. Zájem uživatelů o online pořady postupně slábl, začali zahradničit, péct, chodit do lesa, zkrátka provozovat offline činnosti. Projekt Černá skříňka stojí na pomezí fyzického světa a online virtuální reality   jeho ambice jsou rozloženy v obou prostředích. A právě díky ‒této kombinaci můžeme uvažovat v obou rovinách, jež se nejen vzájemně nevylučují, ale každá poskytuje jisté zázemí a má své specifické kvality.</p>
<p class="l">ČERNÁ SKŘÍŇKA: VÝZVA</p>
<p><i>Galerie TIC chce podpořit vznik umění ve zlomové době. Hledáme umělce, umělkyně nebokolektivy, kteří zpracují a zdokumentují svou zkušenost s koronavirovou pandemií, karanténou a souvisejícím společenským kolapsem, ale i s novou vlnou aktivismu asolidarity. Mohou se například zaměřit na aktuální formy společenské praxe a komunikace,na vizuální trendy, kritiku médií, existenciální krizi, na nároky vůči budoucnosti aj. Jde nám obezprostřední zachycení naší nové situace prostřednictvím uměleckého výzkumu. Materiální, technické nebo konceptuální pojetí je plně na rozhodnutí autorů. Protože jsmekvůli aktuálním opatřením museli vypustit některé součásti výstavního plánu, rozhodli jsmese věnovat uvolněné prostředky na honoráře a náklady na realizaci projektů zapojených dovýzvy. (...)</i></p>
<p>Černá skříňka (Výzva)  [online]. 27. 3. 2020. [cit. 20. 4. 2020]. Dostupné z: http://galerie-tic.cz/aktuality/ </p>
<p>Výzva Galerie TIC byla adresována všem autorům bez omezení, čímž pokračovala tradice otevřených výzev, které jsou vyhlašovány od jejího založení na konci šedesátých let. Během následujících dvou týdnů se sešly podklady od třiceti umělkyň a umělců, z nichž kurátorský tým vybral osm, jež podpořil formou stipendia. Finance byly čerpány z rozpočtu jiných projektů galerie, které nemohly být za stávajících okolností realizovány. Hodnoticím kritériem pro výběr projektů byla naléhavost, autenticita a rozmanitost uměleckých výpovědí.</p>
<br>
<h1>KURÁTOR 02: NOVÝ ARCHIVÁŘ</h1>
<p>Organizačním principem druhého projektu je autorský objekt v podobě umělé inteligence, která interpretuje shromážděný materiál z objektivní, ne-lidské perspektivy. Tento umělý kurátor se zabývá obsahem černé skříňky, aniž by znal kód, v němž je zapsán, a bez povědomí o situaci, v níž vznikl. Podobá se lingvistovi, který objevil neznámý jazyk, nebo mimozemšťanovi, který zachytil neidentifikovatelné signály z planety Země – hledá v nestrukturovaném shluku částic opakující se symboly a zákonitosti jejich uspořádání, aby bylschopen rozluštit znakový systém a rekonstruovat význam obsahu skříňky. Jaké leitmotivy tento nelidský organismus rozpozná ve vizuálních stopách naší zkušenosti s pandemií covidu-19?</p>
<p class="l">NOVÝ ARCHIVÁŘ</p>
<p><i>Ve městě byl jmenován nový archivář. Ale byl skutečně někým jmenován? Nepracuje spíš podle svých vlastních instrukcí? Zlovolní lidé tvrdí, že je novým reprezentantem technologie,strukturální technokracie. (...)  Další tvrdí, že je podvodník, který se nemůže opřít o žádný posvěcený text a který vůbec necituje velké filozofy. Ale jsou naopak i lidé, kteří prohlašují, že se ve filozofii zrodilo něco nového, něco radikálně nového, a že toto dílo má krásu toho, co odmítá: svítání nové doby.</i></p>
<p>DELEUZE, Gilles. Foucault. Praha: Hermann & synové, 2003, s. 11.</p>
<p class="l">DISTANT <s>READING</s></p>
<p>Nový archivář je figurou změny perspektivy i metody práce s archivním materiálem, která je charakterizována hledáním způsobů, jak v rámci poznávání světa překračovat omezení a důsledky jeho antropocentrického výkladu. Deleuze skrze tuto figuru odkazoval k Foucaultovu přínosu k metodologii humanitních věd. My jej využíváme s vědomím významu,který mu dal Deleuze, a současně proto, abychom vyjádřili, v čem spočívá využití metody strojového učení v našem projektu.</p>
<p class="l">UN-SUPERVISED <s>LEARNING</s></p>
<p>Strojové učení představuje podkategorii umělé inteligence, která se v posledních letech intenzivně rozvíjí. Jeho aplikace se využívají především při zpracování rozsáhlých dat. Strojové učení technologicky podporuje rozvoj metody distant reading, která je vhodná pro zkoumání kulturních fenoménů v měřítku velkých dat. Poskytuje poznání založené na kvantifikaci výskytu určitých parametrů datasetu a jejich zpracování s pomocí statistických metod a teorie pravděpodobnosti.</p>
<p>Na rozdíl od close reading, navazujícího na tradici hermeneutické interpretace v humanitníchvědách, se jedná o metodu, jež umožňuje studovat kulturní fenomény na makroúrovni a z hlediska jejich inter- a transmediálního výskytu. Výsledky práce inteligentních algoritmů a jejich vhodné vizualizace umožňují zkoumat vztahy a uspořádání opakujících se motivů. Díky tomu mohou být využity jako opora pro exaktní interpretaci kulturních fenoménů skrze kategorie, jakými jsou klastry jevů, hustota nebo naopak řídkost výskytu v rámci diskurzivních formací.</p>
<p class="l">UN-HUMAN <s>VISION</s></p>
<p>Využití strojového učení pro uspořádání datasetu rozvíjí koncept černé skříňky ve smyslu kapsle uchovávající informace o katastrofě pro případ pozdější rekonstrukce jejích příčin a průběhu. Ne-lidský pohled umělé inteligence na koronavirovou pandemii slouží jako odkaz k Foucaultově deklaraci smrti člověka, stejně jako k pop-kulturní imaginaci postapokalyptické fikce.</p>
<p>V projektu je využita metoda učení bez učitele, která umožňuje prohledávat obrazový materiál – vizuální stopy koronavirové pandemie shromážděné umělci zapojenými do projektu – a třídit jej do předem nedefinovaných souborů na základě podobností rozpoznaných inteligentním algoritmem. Můžeme tak dát před závorku očekávání, předporozumění a emocionální projekci, které tvoří přirozenou součást naší interpretace světa, a nahlédnout stopy pandemie z anestetické distance pohledu nelidského jsoucna.</p>
<br>
<h1>ROZVOJ PROJEKTU</h1>
<p>Cílem projektu je postupně rozšiřovat databázi vizuálních stop pandemie koronaviru a dynamicky aktualizovat naši kolektivní zkušenost. Jedná se o work-in-progress, který je možné průběžně sledovat online.</p>
', '
<h1>CURATOR 01: ONLY ARTISTS WILL SURVIVE</h1>
<p>In this case, the organizational principle is the author subject of the curators. It is an expression of solidarity of the exhibition institution representatives with other actors of contemporary art in times of crisis; an expression of freedom from the restrictions associated with the restrictive preventive measures during quarantine and at the same time a gesture of revolt against the general collective anxiety and sentiment through the artistic research.</p>
<p>The Black Box curatorial project was created at a time when we were experiencing the onset of a pandemic of the new coronavirus Covid-19. On 27 March 2020, the curators of the TIC Brno Gallery and members of the Café Utopia curatorial platform, Katarína Hládeková, Zuzana Janečková and Marika Kupková, called for the collaboration of artists who respond to the corona crisis and thus create a unique record of the catastrophe, thus offering the remarkable clues to understanding of what is happening inside the imaginary black box.</p>
<p>Galleries and museums were closed during the coronavirus quarantine period. From day to day. Unexpectedly. Institutions responded to this situation by creating an online programme: broadcast lectures, guided tours, workshops to replace the standard programme offer. However, these unconvincing attempts at the gallery entertainment could not replace the standard programme. Meaningful ideas, technical equipment and personal experience were missing. In addition, everything was dominated by the overproduction of these activities, which had the opposite effect in result. The interest of the potential users in online programmes gradually vanished as they began to garden, bake, wander in the woods or do the other offline activities. The Black Box project stands on the borderline between the physical world and online virtual reality. Its ambitions are spread across both worlds. And thanks to this combination, we can think on both levels, which are not mutually exclusive, but each provides a certain background and has its own specific qualities.</p>
<p class="l">BLACK BOX: CALL</p>
<p><i>The TIC Brno Gallery wants to support the creation of art at a turning point. We are looking for the artists who will process and document their experience with the corona pandemic, quarantine and related social collapse, but also with a new wave of activism and solidarity. For example, they can focus on current forms of social practice and communication, visual trends, media criticism, existential crisis, demands on the future, etc. We want to capture our new situation immediately through the artistic research. The material, technical or conceptual approach is entirely upon the decision of the authors. As we had to delete some parts of the exhibition plan due to the current measures, we decided to devote the released funds to fees and costs for the implementation of projects involved in the call. (…)</i></p>
<p>Available online at: http://galerie-tic.cz/aktuality/ (released on 27 March 2020, cited on 20 April 2020)</p>
<p>The TIC Brno Gallery call was an addressed to all authors without restriction, thus continuing the tradition of open calls that have been practiced since its foundation in the late 1960s. Over the next two weeks, materials from thirty artists were gathered, from which the curatorial team selected eight, and supported them in the form of scholarships. The funds were drawn from the budget of other gallery projects that could not be implemented under the current circumstances. The evaluation criteria for the selection of projects was the urgency, authenticity and diversity of artistic statements.</p>
<br>
<h1>CURATOR 02: A NEW ARCHIVIST</h1>
<p>The organizational principle of the second project is the author–object in the form of artificial intelligence, which interprets the collected material from an objective, inhuman perspective. This artificial curator deals with the contents of the black box, without knowing the code in which it is written and without having any idea of the situation in which it originated. Similar to a linguist, who discovered an unknown language, or an alien, who intercepted unidentifiable signals from planet Earth, he searches for an unstructured cluster of particles for repetitive symbols and the laws of their arrangement to decipher the sign system and reconstruct the meaning of the box contents. What leitmotifs will this inhuman organism recognize in the visual clues of our experience with the Covid-19 pandemic?</p>
<p class="l">A NEW ARCHIVIST</p>
<p><i>A new archivist has been appointed. But has anyone actually appointed him? Is he not rather acting on his own instructions? Certain malevolent people say that he is the new representative of a structural technology or technocracy. … Some say that he is a shammer who cannot back himself up with reference to the sacred texts, and who seldom quotes the great philosophers. Others, though, claim that something radically new has appeared in philosophy, and that this work is as beautiful as those it challenges. It celebrates the dawn of a new age.</i></p>
<p>DELLEUZE, Gilles: Foucault. London: Continuum, 1999, p. 3.</p>
<p class="l">DISTANT <s>READING</s></p>
<p>The new archivist is a figure of a change in perspective and method of working with archival material, which is characterized by the search for ways to transcend the limitations and consequences of its anthropocentric interpretation in the context of learning about the world. Through this figure, Deleuze referred to Foucault’s contribution to the methodology of the humanities. Intentionally, we use it in the context that Deleuze has given it and at the same time to express what the use of the machine learning method in our project is.</p>
<p class="l">UN-SUPERVISED <s>LEARNING</s></p>
<p>Machine learning is a subcategory of the artificial intelligence discipline, which has been developing intensively in recent years. Its applications are mainly used in the processing of the large data. Machine learning technologically supports the development of the distant reading method, which is suitable for the study of cultural phenomena on a large data scale. It provides knowledge based on the quantification of the certain dataset parameters occurrence and their processing with the help of statistical methods and probability theory.</p>
<p>Unlike close reading, which continues the tradition of hermeneutic interpretation in the humanities, it is a method that allows the study of cultural phenomena at the macro level and in terms of their inter- and trans-media occurrence. The results of the work of intelligent algorithms and their appropriate visualization make it possible to examine the relationships and arrangement of recurring motifs. Thanks to this, they can be used as a support for the exact interpretation of cultural phenomena through categories such as clusters of phenomena, density or, on the other side, the rarity of occurrence within discursive formations.</p>
<p class="l">UN-HUMAN <s>VISION</s></p>
<p>The use of machine learning to organize a dataset develops the concept of the black box in the sense of a capsule storing information about the disaster for a later reconstruction of its causes and course. The non-human view of artificial intelligence on the coronavirus pandemic serves as a reference to Foucault’s declaration of human death as well as to the pop-cultural imagination of postapocalyptic fiction.</p>
<p>In the project, we use a method of unsupervised learning, which allows us to search images – visual traces of a coronavirus pandemic collected by the artists involved in the project – and sort it into predefined files based on intelligent algorithm recognized similarities. Therefore, we can advance the brackets of expectations, preconceptions and emotional projections, that are a natural part of our interpretation of the world, and see traces of a pandemic from an anaesthetic distance of an inhuman being perspective.</p>
<br>
<h1>PROJECT DEVELOPMENT</h1>
<p>The aim of the project is to gradually expand the database of the coronavirus pandemic visual traces and to dynamically update our collective experience. It is a work-in-progress that can be monitored online on an ongoing basis.</p>
');

echo findLinks($text);
